POST http://localhost:3000/api/v1/drivers
content-type: application/json
Accept: application/json

{
  "firtname": "hola",
  "lastname": "22asd",
  "document": "12345678901",
  "phone": "1234567890",
  "street": "123asd"
}

###
GET http://localhost:3000/api/v1/drivers
content-type: application/json
Accept: application/json

