POST http://localhost:3000/api/v1/vehicles
content-type: application/json
Accept: application/json

{
  "capacity": "hola",
  "model": "22as",
  "plate": "21a3534"
}

### obtener todos los vehiculos
GET http://localhost:3000/api/v1/vehicles
content-type: application/json
Accept: application/json

### asosicar un conductor con un vehiculo
POST http://localhost:3000/api/v1/vehicles/modifyAssociation
content-type: application/json
Accept: application/json

{
  "driverId": 5,
  "vehicleId": 5,
  "disassociate": true
}

